### ISSUE TITLE
Symbology wrong when pulling from CSV but okay when pulling from DBF in some cases

### ISSUE THREAD

**Issue by sdrewc** [sfcta/simwrapper#24]
The TNC 2020 visualization (http://prospector/simwrapper/champ/Miscellaneous/viz-map-tncs2020.yaml) uses Census zip code tabulation areas (ZCTAs), and includes a shapefile, dbf, and csv.  The contents of the DBF and CSV are identical.  Selecting a field (for example, "vmt") from the DBF file works as expected, but selecting the same field from the CSV yields different and incorrect results.

**Comment by sdrewc** [comment]
I think this may be caused by simwrapper incorrectly imputing a string data type for a numeric field when some of the cell values are blank.

**Comment by billyc** [comment]
@sdrewc @bhargavasana @joecastiglione  - thanks for finding the likely cause on this one!

I copied those files locally in order to debug, but I don't see the `est_file_all_zcta.DBF` version. I can create that myself from the CSV but I'm not seeing the error.

Can you provide me with files that trigger this problem?

**Comment by sdrewc** [comment]
@billyc sorry, I forgot I linked to the viz in this issue and edited it.  This one is a good example of the issue: http://prospector/simwrapper/champ/Miscellaneous/viz-map-tncs2020_uber.yaml .  The files are ../shapefiles/ZCTA/zcta_uber_prj.shp and ./zcta_uber.csv

**Comment by billyc** [comment]
@sdrewc and is there a DBF ?  You said the DBF is working? I want the DBF too! :-)

**Comment by bhargavasana** [comment]
It looks like this has been fixed in the latest update!
- http://prospector/simwrapper/champ/Miscellaneous/viz-map-tncs2020_uber.yaml
- http://prospector/simwrapper/champ/Miscellaneous/viz-map-tncs2020_uber-dbf.yaml

**Comment by sdrewc** [comment]
Agree, looks good.
