### ISSUE TITLE
Fill height normalization produces counterintuitive results

### ISSUE THREAD

**Issue by joecastiglione** [sfcta/simwrapper#25]
When using normalized fill heights (eg. HHs normalized by area), the heights clearly don't correspond to the normalized values, with lower values sometimes appearing "taller" than higher values.

**Comment by joecastiglione** [comment]
Wanted to provide an illustration of strange fill height results.  This shows avg weekly TNC pickups by TAZ, normalized by SQ_MI.  In the first image, the really tall pink zone has an implied TNC trip density of 100,388.5 trip/sqmi.  In the second image, the really short pink zone has an implied TNC trip density of 207,663.0 trips/sqmi.  Shouldn't this zone be 2x as tall as the first zone, not 1/50th as tall?
 
![fillheight_1](https://user-images.githubusercontent.com/4674591/174867866-97a75c30-30d3-4a29-aab7-3f58eedee159.jpg)
![fillheight_2](https://user-images.githubusercontent.com/4674591/174867890-8f237149-f786-48e8-819a-e830440b2891.jpg)

**Comment by billyc** [comment]
Fixed as in #24
