### ISSUE TITLE
Symbology Limitation When Few Discrete Values

### ISSUE THREAD

**Issue by joecastiglione** [sfcta/simwrapper#26]
Example:  I have a TAZ dataset with variable called PLACETYPE, which has 3 values (1,2,3).  When I set the number of steps to 3, I get this strange binning where the classes are 0-0, 0-1, 1-3, so all the values TAZs are assigned the same color (based on the 1-3) bin.  Please see the legend in image below.

![fillheight_1](https://user-images.githubusercontent.com/4674591/174869236-9da12f6f-6a07-4a0a-9e8a-836d332c1d51.jpg)

**Comment by billyc** [comment]
@joecastiglione @bhargavasana  with the "categorical" color selections I think this is fixed now? Or do you need anything further for us to mark this issue closed?

**Comment by bhargavasana** [comment]
It is working well! In a future enhancement, we could add the ability to specify a fixed color for each discrete value in the yaml file.
