### ISSUE TITLE
Save view angle and rotation for 3d maps in yaml

### ISSUE THREAD

**Issue by sdrewc** [sfcta/simwrapper#27]
After creating a 3d map and exporting the yaml file, the angle and rotation of the new map are reset to default

**Comment by billyc** [comment]
We already have `center` and `zoom`

Now we also have
- `bearing` -- the angle (from North)
- `pitch` -- the 3D angle (?) between 0 (default) and 90

**Comment by sdrewc** [comment]
Awesome!  Just tested setting these and they worked just as expected.  Can these also exported with the "save YAML config" option?

**Comment by billyc** [comment]
Yes, fixed.
